
INSERT INTO country (country_sk, data) VALUES (3924, '{"gdp": 11937562, "region": "Eastern Asia", "continent": "Asia", "population": 1409517397, "country_name": "China"}');
INSERT INTO country (country_sk, data) VALUES (3925, '{"gdp": 2439008, "region": "Southern Asia", "continent": "Asia", "population": 1339180127, "country_name": "India"}');
INSERT INTO country (country_sk, data) VALUES (3926, '{"gdp": 19362129, "region": "Northern America", "continent": "Americas", "population": 324459463, "country_name": "United States"}');
INSERT INTO country (country_sk, data) VALUES (3927, '{"gdp": 1010937, "region": "South-eastern Asia", "continent": "Asia", "population": 263991379, "country_name": "Indonesia"}');
INSERT INTO country (country_sk, data) VALUES (3928, '{"gdp": 2080916, "region": "South America", "continent": "Americas", "population": 209288278, "country_name": "Brazil"}');
INSERT INTO country (country_sk, data) VALUES (3929, '{"gdp": 304400, "region": "Southern Asia", "continent": "Asia", "population": 197015955, "country_name": "Pakistan"}');
INSERT INTO country (country_sk, data) VALUES (3930, '{"gdp": 394818, "region": "Western Africa", "continent": "Africa", "population": 190886311, "country_name": "Nigeria"}');
INSERT INTO country (country_sk, data) VALUES (3931, '{"gdp": 250023, "region": "Southern Asia", "continent": "Asia", "population": 164669751, "country_name": "Bangladesh"}');
INSERT INTO country (country_sk, data) VALUES (3932, '{"gdp": 1469341, "region": "Eastern Europe", "continent": "Europe", "population": 143989754, "country_name": "Russia"}');
INSERT INTO country (country_sk, data) VALUES (3933, '{"gdp": 1142453, "region": "Central America", "continent": "Americas", "population": 129163276, "country_name": "Mexico"}');
INSERT INTO country (country_sk, data) VALUES (3934, '{"gdp": 4884489, "region": "Eastern Asia", "continent": "Asia", "population": 127484450, "country_name": "Japan"}');
INSERT INTO country (country_sk, data) VALUES (3935, '{"gdp": 79735, "region": "Eastern Africa", "continent": "Africa", "population": 104957438, "country_name": "Ethiopia"}');
INSERT INTO country (country_sk, data) VALUES (3936, '{"gdp": 321189, "region": "South-eastern Asia", "continent": "Asia", "population": 104918090, "country_name": "Philippines"}');
INSERT INTO country (country_sk, data) VALUES (3937, '{"gdp": 408045, "region": "Northern Africa", "continent": "Africa", "population": 97553151, "country_name": "Egypt"}');
INSERT INTO country (country_sk, data) VALUES (3938, '{"gdp": 215963, "region": "South-eastern Asia", "continent": "Asia", "population": 95540800, "country_name": "Vietnam"}');
INSERT INTO country (country_sk, data) VALUES (3939, '{"gdp": 3651871, "region": "Western Europe", "continent": "Europe", "population": 82114224, "country_name": "Germany"}');
INSERT INTO country (country_sk, data) VALUES (3940, '{"gdp": 7799, "region": "Middle Africa", "continent": "Africa", "population": 81339988, "country_name": "Democratic Republic of the Congo"}');
INSERT INTO country (country_sk, data) VALUES (3941, '{"gdp": 427666, "region": "Southern Asia", "continent": "Asia", "population": 81162788, "country_name": "Iran"}');
INSERT INTO country (country_sk, data) VALUES (3942, '{"gdp": 841206, "region": "Western Asia", "continent": "Asia", "population": 80745020, "country_name": "Turkey"}');
INSERT INTO country (country_sk, data) VALUES (3943, '{"gdp": 437807, "region": "South-eastern Asia", "continent": "Asia", "population": 69037513, "country_name": "Thailand"}');
INSERT INTO country (country_sk, data) VALUES (3944, '{"gdp": 2565051, "region": "Northern Europe", "continent": "Europe", "population": 66181585, "country_name": "United Kingdom"}');
INSERT INTO country (country_sk, data) VALUES (3945, '{"gdp": 2574807, "region": "Western Europe", "continent": "Europe", "population": 64979548, "country_name": "France"}');
INSERT INTO country (country_sk, data) VALUES (3946, '{"gdp": 1921139, "region": "Southern Europe", "continent": "Europe", "population": 59359900, "country_name": "Italy"}');
INSERT INTO country (country_sk, data) VALUES (3947, '{"gdp": 51614, "region": "Eastern Africa", "continent": "Africa", "population": 57310019, "country_name": "Tanzania"}');
INSERT INTO country (country_sk, data) VALUES (3948, '{"gdp": 344064, "region": "Southern Africa", "continent": "Africa", "population": 56717156, "country_name": "South Africa"}');
INSERT INTO country (country_sk, data) VALUES (3949, '{"gdp": 66966, "region": "South-eastern Asia", "continent": "Asia", "population": 53370609, "country_name": "Myanmar"}');
INSERT INTO country (country_sk, data) VALUES (3950, '{"gdp": 1529743, "region": "Eastern Asia", "continent": "Asia", "population": 50982212, "country_name": "South Korea"}');
INSERT INTO country (country_sk, data) VALUES (3951, '{"gdp": 307475, "region": "South America", "continent": "Americas", "population": 49065615, "country_name": "Colombia"}');
INSERT INTO country (country_sk, data) VALUES (3952, '{"gdp": 78397, "region": "Eastern Africa", "continent": "Africa", "population": 49699862, "country_name": "Kenya"}');
INSERT INTO country (country_sk, data) VALUES (3953, '{"gdp": 1307170, "region": "Southern Europe", "continent": "Europe", "population": 46354321, "country_name": "Spain"}');
INSERT INTO country (country_sk, data) VALUES (3954, '{"gdp": 619872, "region": "South America", "continent": "Americas", "population": 44271041, "country_name": "Argentina"}');
INSERT INTO country (country_sk, data) VALUES (3955, '{"gdp": 104062, "region": "Eastern Europe", "continent": "Europe", "population": 44222947, "country_name": "Ukraine"}');
INSERT INTO country (country_sk, data) VALUES (3956, '{"gdp": 26391, "region": "Eastern Africa", "continent": "Africa", "population": 42862958, "country_name": "Uganda"}');
INSERT INTO country (country_sk, data) VALUES (3957, '{"gdp": 175493, "region": "Northern Africa", "continent": "Africa", "population": 41318142, "country_name": "Algeria"}');
INSERT INTO country (country_sk, data) VALUES (3958, '{"gdp": 118979, "region": "Northern Africa", "continent": "Africa", "population": 40533330, "country_name": "Sudan"}');
INSERT INTO country (country_sk, data) VALUES (3959, '{"gdp": 192660, "region": "Western Asia", "continent": "Asia", "population": 38274618, "country_name": "Iraq"}');
INSERT INTO country (country_sk, data) VALUES (3960, '{"gdp": 509955, "region": "Eastern Europe", "continent": "Europe", "population": 38170712, "country_name": "Poland"}');
INSERT INTO country (country_sk, data) VALUES (3961, '{"gdp": 1640385, "region": "Northern America", "continent": "Americas", "population": 36624199, "country_name": "Canada"}');
INSERT INTO country (country_sk, data) VALUES (3962, '{"gdp": 110708, "region": "Northern Africa", "continent": "Africa", "population": 35739580, "country_name": "Morocco"}');
INSERT INTO country (country_sk, data) VALUES (3963, '{"gdp": 21056, "region": "Southern Asia", "continent": "Asia", "population": 35530081, "country_name": "Afghanistan"}');
INSERT INTO country (country_sk, data) VALUES (3964, '{"gdp": 678541, "region": "Western Asia", "continent": "Asia", "population": 32938213, "country_name": "Saudi Arabia"}');
INSERT INTO country (country_sk, data) VALUES (3965, '{"gdp": 210013, "region": "South America", "continent": "Americas", "population": 32165485, "country_name": "Peru"}');
INSERT INTO country (country_sk, data) VALUES (3966, '{"gdp": 215307, "region": "South America", "continent": "Americas", "population": 31977065, "country_name": "Venezuela"}');
INSERT INTO country (country_sk, data) VALUES (3967, '{"gdp": 67505, "region": "Central Asia", "continent": "Asia", "population": 31910641, "country_name": "Uzbekistan"}');
INSERT INTO country (country_sk, data) VALUES (3968, '{"gdp": 309858, "region": "South-eastern Asia", "continent": "Asia", "population": 31624264, "country_name": "Malaysia"}');
INSERT INTO country (country_sk, data) VALUES (3969, '{"gdp": 124034, "region": "Middle Africa", "continent": "Africa", "population": 29784193, "country_name": "Angola"}');
INSERT INTO country (country_sk, data) VALUES (3970, '{"gdp": 12345, "region": "Eastern Africa", "continent": "Africa", "population": 29668834, "country_name": "Mozambique"}');
INSERT INTO country (country_sk, data) VALUES (3971, '{"gdp": 24065, "region": "Southern Asia", "continent": "Asia", "population": 29304998, "country_name": "Nepal"}');
INSERT INTO country (country_sk, data) VALUES (3972, '{"gdp": 45464, "region": "Western Africa", "continent": "Africa", "population": 28833629, "country_name": "Ghana"}');
INSERT INTO country (country_sk, data) VALUES (3973, '{"gdp": 25663, "region": "Western Asia", "continent": "Asia", "population": 28250420, "country_name": "Yemen"}');
INSERT INTO country (country_sk, data) VALUES (3974, '{"gdp": 10557, "region": "Eastern Africa", "continent": "Africa", "population": 25570895, "country_name": "Madagascar"}');
INSERT INTO country (country_sk, data) VALUES (3975, '{"gdp": null, "region": "Eastern Asia", "continent": "Asia", "population": 25490965, "country_name": "North Korea"}');
INSERT INTO country (country_sk, data) VALUES (3976, '{"gdp": 1390150, "region": "Australia�and�New Zealand", "continent": "Oceania", "population": 24450561, "country_name": "Australia"}');
INSERT INTO country (country_sk, data) VALUES (3977, '{"gdp": 39906, "region": "Western Africa", "continent": "Africa", "population": 24294750, "country_name": "Ivory Coast"}');
INSERT INTO country (country_sk, data) VALUES (3978, '{"gdp": 30652, "region": "Middle Africa", "continent": "Africa", "population": 24053727, "country_name": "Cameroon"}');
INSERT INTO country (country_sk, data) VALUES (3979, '{"gdp": 571453, "region": "Eastern Asia", "continent": "Asia", "population": 23626456, "country_name": "Taiwan"}');
INSERT INTO country (country_sk, data) VALUES (3980, '{"gdp": 7892, "region": "Western Africa", "continent": "Africa", "population": 21477348, "country_name": "Niger"}');
INSERT INTO country (country_sk, data) VALUES (3981, '{"gdp": 83567, "region": "Southern Asia", "continent": "Asia", "population": 20876917, "country_name": "Sri Lanka"}');
INSERT INTO country (country_sk, data) VALUES (3982, '{"gdp": 204943, "region": "Eastern Europe", "continent": "Europe", "population": 19679306, "country_name": "Romania"}');
INSERT INTO country (country_sk, data) VALUES (3983, '{"gdp": 13187, "region": "Western Africa", "continent": "Africa", "population": 19193382, "country_name": "Burkina Faso"}');
INSERT INTO country (country_sk, data) VALUES (3984, '{"gdp": 6261, "region": "Eastern Africa", "continent": "Africa", "population": 18622104, "country_name": "Malawi"}');
INSERT INTO country (country_sk, data) VALUES (3985, '{"gdp": 14998, "region": "Western Africa", "continent": "Africa", "population": 18541980, "country_name": "Mali"}');
INSERT INTO country (country_sk, data) VALUES (3986, '{"gdp": 77460, "region": "Western Asia", "continent": "Asia", "population": 18269868, "country_name": "Syria"}');
INSERT INTO country (country_sk, data) VALUES (3987, '{"gdp": 156189, "region": "Central Asia", "continent": "Asia", "population": 18204499, "country_name": "Kazakhstan"}');
INSERT INTO country (country_sk, data) VALUES (3988, '{"gdp": 263206, "region": "South America", "continent": "Americas", "population": 18054726, "country_name": "Chile"}');
INSERT INTO country (country_sk, data) VALUES (3989, '{"gdp": 25576, "region": "Eastern Africa", "continent": "Africa", "population": 17094130, "country_name": "Zambia"}');
INSERT INTO country (country_sk, data) VALUES (3990, '{"gdp": 824480, "region": "Western Europe", "continent": "Europe", "population": 17035938, "country_name": "Netherlands"}');
INSERT INTO country (country_sk, data) VALUES (3991, '{"gdp": 70806, "region": "Central America", "continent": "Americas", "population": 16913503, "country_name": "Guatemala"}');
INSERT INTO country (country_sk, data) VALUES (3992, '{"gdp": 98576, "region": "South America", "continent": "Americas", "population": 16624858, "country_name": "Ecuador"}');
INSERT INTO country (country_sk, data) VALUES (3993, '{"gdp": 17105, "region": "Eastern Africa", "continent": "Africa", "population": 16529904, "country_name": "Zimbabwe"}');
INSERT INTO country (country_sk, data) VALUES (3994, '{"gdp": 22252, "region": "South-eastern Asia", "continent": "Asia", "population": 16005373, "country_name": "Cambodia"}');
INSERT INTO country (country_sk, data) VALUES (3995, '{"gdp": 16057, "region": "Western Africa", "continent": "Africa", "population": 15850567, "country_name": "Senegal"}');
INSERT INTO country (country_sk, data) VALUES (3996, '{"gdp": 9740, "region": "Middle Africa", "continent": "Africa", "population": 14899994, "country_name": "Chad"}');
INSERT INTO country (country_sk, data) VALUES (3997, '{"gdp": null, "region": "Eastern Africa", "continent": "Africa", "population": 14742523, "country_name": "Somalia"}');
INSERT INTO country (country_sk, data) VALUES (3998, '{"gdp": 9183, "region": "Western Africa", "continent": "Africa", "population": 12717176, "country_name": "Guinea"}');
INSERT INTO country (country_sk, data) VALUES (3999, '{"gdp": 2915, "region": "Eastern Africa", "continent": "Africa", "population": 12575714, "country_name": "South Sudan"}');
INSERT INTO country (country_sk, data) VALUES (4000, '{"gdp": 8918, "region": "Eastern Africa", "continent": "Africa", "population": 12208407, "country_name": "Rwanda"}');
INSERT INTO country (country_sk, data) VALUES (4001, '{"gdp": 39883, "region": "Northern Africa", "continent": "Africa", "population": 11532127, "country_name": "Tunisia"}');
INSERT INTO country (country_sk, data) VALUES (4002, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 11484636, "country_name": "Cuba"}');
INSERT INTO country (country_sk, data) VALUES (4003, '{"gdp": 491672, "region": "Western Europe", "continent": "Europe", "population": 11429336, "country_name": "Belgium"}');
INSERT INTO country (country_sk, data) VALUES (4004, '{"gdp": 9410, "region": "Western Africa", "continent": "Africa", "population": 11175692, "country_name": "Benin"}');
INSERT INTO country (country_sk, data) VALUES (4005, '{"gdp": 204299, "region": "Southern Europe", "continent": "Europe", "population": 11159773, "country_name": "Greece"}');
INSERT INTO country (country_sk, data) VALUES (4006, '{"gdp": 37776, "region": "South America", "continent": "Americas", "population": 11051600, "country_name": "Bolivia"}');
INSERT INTO country (country_sk, data) VALUES (4007, '{"gdp": 8360, "region": "Caribbean", "continent": "Americas", "population": 10981229, "country_name": "Haiti"}');
INSERT INTO country (country_sk, data) VALUES (4008, '{"gdp": 3393, "region": "Eastern Africa", "continent": "Africa", "population": 10864245, "country_name": "Burundi"}');
INSERT INTO country (country_sk, data) VALUES (4009, '{"gdp": 74837, "region": "Caribbean", "continent": "Americas", "population": 10766998, "country_name": "Dominican Republic"}');
INSERT INTO country (country_sk, data) VALUES (4010, '{"gdp": 209652, "region": "Eastern Europe", "continent": "Europe", "population": 10618303, "country_name": "Czech Republic"}');
INSERT INTO country (country_sk, data) VALUES (4011, '{"gdp": 211696, "region": "Southern Europe", "continent": "Europe", "population": 10329506, "country_name": "Portugal"}');
INSERT INTO country (country_sk, data) VALUES (4012, '{"gdp": 541889, "region": "Northern Europe", "continent": "Europe", "population": 9910701, "country_name": "Sweden"}');
INSERT INTO country (country_sk, data) VALUES (4013, '{"gdp": 39207, "region": "Western Asia", "continent": "Asia", "population": 9827589, "country_name": "Azerbaijan"}');
INSERT INTO country (country_sk, data) VALUES (4014, '{"gdp": 132034, "region": "Eastern Europe", "continent": "Europe", "population": 9721559, "country_name": "Hungary"}');
INSERT INTO country (country_sk, data) VALUES (4015, '{"gdp": 40487, "region": "Western Asia", "continent": "Asia", "population": 9702353, "country_name": "Jordan"}');
INSERT INTO country (country_sk, data) VALUES (4016, '{"gdp": 52783, "region": "Eastern Europe", "continent": "Europe", "population": 9468338, "country_name": "Belarus"}');
INSERT INTO country (country_sk, data) VALUES (4017, '{"gdp": 378656, "region": "Western Asia", "continent": "Asia", "population": 9400145, "country_name": "United Arab Emirates"}');
INSERT INTO country (country_sk, data) VALUES (4018, '{"gdp": 22675, "region": "Central America", "continent": "Americas", "population": 9265067, "country_name": "Honduras"}');
INSERT INTO country (country_sk, data) VALUES (4019, '{"gdp": 7234, "region": "Central Asia", "continent": "Asia", "population": 8921343, "country_name": "Tajikistan"}');
INSERT INTO country (country_sk, data) VALUES (4020, '{"gdp": 39366, "region": "Southern Europe", "continent": "Europe", "population": 8790574, "country_name": "Serbia"}');
INSERT INTO country (country_sk, data) VALUES (4021, '{"gdp": 409316, "region": "Western Europe", "continent": "Europe", "population": 8735453, "country_name": "Austria"}');
INSERT INTO country (country_sk, data) VALUES (4022, '{"gdp": 680645, "region": "Western Europe", "continent": "Europe", "population": 8476005, "country_name": "Switzerland"}');
INSERT INTO country (country_sk, data) VALUES (4023, '{"gdp": 348006, "region": "Western Asia", "continent": "Asia", "population": 8321570, "country_name": "Israel"}');
INSERT INTO country (country_sk, data) VALUES (4024, '{"gdp": 21811, "region": "Melanesia", "continent": "Oceania", "population": 8251162, "country_name": "Papua New Guinea"}');
INSERT INTO country (country_sk, data) VALUES (4025, '{"gdp": 4797, "region": "Western Africa", "continent": "Africa", "population": 7797694, "country_name": "Togo"}');
INSERT INTO country (country_sk, data) VALUES (4026, '{"gdp": 3897, "region": "Western Africa", "continent": "Africa", "population": 7557212, "country_name": "Sierra Leone"}');
INSERT INTO country (country_sk, data) VALUES (4027, '{"gdp": 334104, "region": "Eastern Asia", "continent": "Asia", "population": 7364883, "country_name": "Hong Kong"}');
INSERT INTO country (country_sk, data) VALUES (4028, '{"gdp": 55954, "region": "Eastern Europe", "continent": "Europe", "population": 7084571, "country_name": "Bulgaria"}');
INSERT INTO country (country_sk, data) VALUES (4029, '{"gdp": 17152, "region": "South-eastern Asia", "continent": "Asia", "population": 6858160, "country_name": "Laos"}');
INSERT INTO country (country_sk, data) VALUES (4030, '{"gdp": 28780, "region": "South America", "continent": "Americas", "population": 6811297, "country_name": "Paraguay"}');
INSERT INTO country (country_sk, data) VALUES (4031, '{"gdp": 27407, "region": "Central America", "continent": "Americas", "population": 6377853, "country_name": "El Salvador"}');
INSERT INTO country (country_sk, data) VALUES (4032, '{"gdp": 33314, "region": "Northern Africa", "continent": "Africa", "population": 6374616, "country_name": "Libya"}');
INSERT INTO country (country_sk, data) VALUES (4033, '{"gdp": 13692, "region": "Central America", "continent": "Americas", "population": 6217581, "country_name": "Nicaragua"}');
INSERT INTO country (country_sk, data) VALUES (4034, '{"gdp": 52698, "region": "Western Asia", "continent": "Asia", "population": 6082357, "country_name": "Lebanon"}');
INSERT INTO country (country_sk, data) VALUES (4035, '{"gdp": 7061, "region": "Central Asia", "continent": "Asia", "population": 6045117, "country_name": "Kyrgyzstan"}');
INSERT INTO country (country_sk, data) VALUES (4036, '{"gdp": 41670, "region": "Central Asia", "continent": "Asia", "population": 5758075, "country_name": "Turkmenistan"}');
INSERT INTO country (country_sk, data) VALUES (4037, '{"gdp": 324146, "region": "Northern Europe", "continent": "Europe", "population": 5733551, "country_name": "Denmark"}');
INSERT INTO country (country_sk, data) VALUES (4038, '{"gdp": 305757, "region": "South-eastern Asia", "continent": "Asia", "population": 5708844, "country_name": "Singapore"}');
INSERT INTO country (country_sk, data) VALUES (4039, '{"gdp": 251381, "region": "Northern Europe", "continent": "Europe", "population": 5523231, "country_name": "Finland"}');
INSERT INTO country (country_sk, data) VALUES (4040, '{"gdp": 94997, "region": "Eastern Europe", "continent": "Europe", "population": 5447662, "country_name": "Slovakia"}');
INSERT INTO country (country_sk, data) VALUES (4041, '{"gdp": 392052, "region": "Northern Europe", "continent": "Europe", "population": 5305383, "country_name": "Norway"}');
INSERT INTO country (country_sk, data) VALUES (4042, '{"gdp": null, "region": "Middle Africa", "continent": "Africa", "population": 5260750, "country_name": "Congo"}');
INSERT INTO country (country_sk, data) VALUES (4043, '{"gdp": 6050, "region": "Eastern Africa", "continent": "Africa", "population": 5068831, "country_name": "Eritrea"}');
INSERT INTO country (country_sk, data) VALUES (4044, '{"gdp": null, "region": "Western Asia", "continent": "Asia", "population": 4920724, "country_name": "Palestine"}');
INSERT INTO country (country_sk, data) VALUES (4045, '{"gdp": 58909, "region": "Central America", "continent": "Americas", "population": 4905769, "country_name": "Costa Rica"}');
INSERT INTO country (country_sk, data) VALUES (4046, '{"gdp": 325649, "region": "Northern Europe", "continent": "Europe", "population": 4761657, "country_name": "Ireland"}');
INSERT INTO country (country_sk, data) VALUES (4047, '{"gdp": 2140, "region": "Western Africa", "continent": "Africa", "population": 4731906, "country_name": "Liberia"}');
INSERT INTO country (country_sk, data) VALUES (4048, '{"gdp": 200837, "region": "Australia�and�New Zealand", "continent": "Oceania", "population": 4705818, "country_name": "New Zealand"}');
INSERT INTO country (country_sk, data) VALUES (4049, '{"gdp": 1992, "region": "Middle Africa", "continent": "Africa", "population": 4659080, "country_name": "Central African Republic"}');
INSERT INTO country (country_sk, data) VALUES (4050, '{"gdp": 71931, "region": "Western Asia", "continent": "Asia", "population": 4636262, "country_name": "Oman"}');
INSERT INTO country (country_sk, data) VALUES (4051, '{"gdp": 4985, "region": "Western Africa", "continent": "Africa", "population": 4420184, "country_name": "Mauritania"}');
INSERT INTO country (country_sk, data) VALUES (4052, '{"gdp": 53481, "region": "Southern Europe", "continent": "Europe", "population": 4189353, "country_name": "Croatia"}');
INSERT INTO country (country_sk, data) VALUES (4053, '{"gdp": 118271, "region": "Western Asia", "continent": "Asia", "population": 4136528, "country_name": "Kuwait"}');
INSERT INTO country (country_sk, data) VALUES (4054, '{"gdp": 59051, "region": "Central America", "continent": "Americas", "population": 4098587, "country_name": "Panama"}');
INSERT INTO country (country_sk, data) VALUES (4055, '{"gdp": 7945, "region": "Eastern Europe", "continent": "Europe", "population": 4051212, "country_name": "Moldova"}');
INSERT INTO country (country_sk, data) VALUES (4056, '{"gdp": 15230, "region": "Western Asia", "continent": "Asia", "population": 3912061, "country_name": "Georgia"}');
INSERT INTO country (country_sk, data) VALUES (4057, '{"gdp": 103243, "region": "Caribbean", "continent": "Americas", "population": 3663131, "country_name": "Puerto Rico"}');
INSERT INTO country (country_sk, data) VALUES (4058, '{"gdp": 17457, "region": "Southern Europe", "continent": "Europe", "population": 3507017, "country_name": "Bosnia and Herzegovina"}');
INSERT INTO country (country_sk, data) VALUES (4059, '{"gdp": 60266, "region": "South America", "continent": "Americas", "population": 3456750, "country_name": "Uruguay"}');
INSERT INTO country (country_sk, data) VALUES (4060, '{"gdp": 10869, "region": "Eastern Asia", "continent": "Asia", "population": 3075647, "country_name": "Mongolia"}');
INSERT INTO country (country_sk, data) VALUES (4061, '{"gdp": 11037, "region": "Western Asia", "continent": "Asia", "population": 2930450, "country_name": "Armenia"}');
INSERT INTO country (country_sk, data) VALUES (4062, '{"gdp": 13001, "region": "Southern Europe", "continent": "Europe", "population": 2930187, "country_name": "Albania"}');
INSERT INTO country (country_sk, data) VALUES (4063, '{"gdp": 14290, "region": "Caribbean", "continent": "Americas", "population": 2890299, "country_name": "Jamaica"}');
INSERT INTO country (country_sk, data) VALUES (4064, '{"gdp": 46666, "region": "Northern Europe", "continent": "Europe", "population": 2890297, "country_name": "Lithuania"}');
INSERT INTO country (country_sk, data) VALUES (4065, '{"gdp": 166346, "region": "Western Asia", "continent": "Asia", "population": 2639211, "country_name": "Qatar"}');
INSERT INTO country (country_sk, data) VALUES (4066, '{"gdp": 12558, "region": "Southern Africa", "continent": "Africa", "population": 2533794, "country_name": "Namibia"}');
INSERT INTO country (country_sk, data) VALUES (4067, '{"gdp": 16725, "region": "Southern Africa", "continent": "Africa", "population": 2291661, "country_name": "Botswana"}');
INSERT INTO country (country_sk, data) VALUES (4068, '{"gdp": 2721, "region": "Southern Africa", "continent": "Africa", "population": 2233339, "country_name": "Lesotho"}');
INSERT INTO country (country_sk, data) VALUES (4069, '{"gdp": 1038, "region": "Western Africa", "continent": "Africa", "population": 2100568, "country_name": "The Gambia"}');
INSERT INTO country (country_sk, data) VALUES (4070, '{"gdp": 11416, "region": "Southern Europe", "continent": "Europe", "population": 2083160, "country_name": "Republic of Macedonia"}');
INSERT INTO country (country_sk, data) VALUES (4071, '{"gdp": 48078, "region": "Southern Europe", "continent": "Europe", "population": 2079976, "country_name": "Slovenia"}');
INSERT INTO country (country_sk, data) VALUES (4072, '{"gdp": 14467, "region": "Middle Africa", "continent": "Africa", "population": 2025137, "country_name": "Gabon"}');
INSERT INTO country (country_sk, data) VALUES (4073, '{"gdp": 30176, "region": "Northern Europe", "continent": "Europe", "population": 1949670, "country_name": "Latvia"}');
INSERT INTO country (country_sk, data) VALUES (4074, '{"gdp": 1295, "region": "Western Africa", "continent": "Africa", "population": 1861283, "country_name": "Guinea-Bissau"}');
INSERT INTO country (country_sk, data) VALUES (4075, '{"gdp": 33873, "region": "Western Asia", "continent": "Asia", "population": 1492584, "country_name": "Bahrain"}');
INSERT INTO country (country_sk, data) VALUES (4076, '{"gdp": 20300, "region": "Caribbean", "continent": "Americas", "population": 1369125, "country_name": "Trinidad and Tobago"}');
INSERT INTO country (country_sk, data) VALUES (4077, '{"gdp": 4030, "region": "Southern Africa", "continent": "Africa", "population": 1367254, "country_name": "Swaziland"}');
INSERT INTO country (country_sk, data) VALUES (4078, '{"gdp": 25683, "region": "Northern Europe", "continent": "Europe", "population": 1309632, "country_name": "Estonia"}');
INSERT INTO country (country_sk, data) VALUES (4079, '{"gdp": 2716, "region": "South-eastern Asia", "continent": "Asia", "population": 1296311, "country_name": "East Timor"}');
INSERT INTO country (country_sk, data) VALUES (4080, '{"gdp": 10069, "region": "Middle Africa", "continent": "Africa", "population": 1267689, "country_name": "Equatorial Guinea"}');
INSERT INTO country (country_sk, data) VALUES (4081, '{"gdp": 12273, "region": "Eastern Africa", "continent": "Africa", "population": 1265138, "country_name": "Mauritius"}');
INSERT INTO country (country_sk, data) VALUES (4082, '{"gdp": 21109, "region": "Western Asia", "continent": "Asia", "population": 1179551, "country_name": "Cyprus"}');
INSERT INTO country (country_sk, data) VALUES (4083, '{"gdp": 2082, "region": "Eastern Africa", "continent": "Africa", "population": 956985, "country_name": "Djibouti"}');
INSERT INTO country (country_sk, data) VALUES (4084, '{"gdp": 5054, "region": "Melanesia", "continent": "Oceania", "population": 905502, "country_name": "Fiji"}');
INSERT INTO country (country_sk, data) VALUES (4085, '{"gdp": null, "region": "Eastern Africa", "continent": "Africa", "population": 876562, "country_name": "R�union"}');
INSERT INTO country (country_sk, data) VALUES (4086, '{"gdp": 659, "region": "Eastern Africa", "continent": "Africa", "population": 813912, "country_name": "Comoros"}');
INSERT INTO country (country_sk, data) VALUES (4087, '{"gdp": 2321, "region": "Southern Asia", "continent": "Asia", "population": 807610, "country_name": "Bhutan"}');
INSERT INTO country (country_sk, data) VALUES (4088, '{"gdp": 3591, "region": "South America", "continent": "Americas", "population": 777859, "country_name": "Guyana"}');
INSERT INTO country (country_sk, data) VALUES (4089, '{"gdp": 4405, "region": "Southern Europe", "continent": "Europe", "population": 628960, "country_name": "Montenegro"}');
INSERT INTO country (country_sk, data) VALUES (4090, '{"gdp": 51160, "region": "Eastern Asia", "continent": "Asia", "population": 622567, "country_name": "Macau"}');
INSERT INTO country (country_sk, data) VALUES (4091, '{"gdp": 1273, "region": "Melanesia", "continent": "Oceania", "population": 611343, "country_name": "Solomon Islands"}');
INSERT INTO country (country_sk, data) VALUES (4092, '{"gdp": 63517, "region": "Western Europe", "continent": "Europe", "population": 583455, "country_name": "Luxembourg"}');
INSERT INTO country (country_sk, data) VALUES (4093, '{"gdp": 3665, "region": "South America", "continent": "Americas", "population": 563402, "country_name": "Suriname"}');
INSERT INTO country (country_sk, data) VALUES (4094, '{"gdp": null, "region": "Northern Africa", "continent": "Africa", "population": 552628, "country_name": "Western Sahara"}');
INSERT INTO country (country_sk, data) VALUES (4095, '{"gdp": 1728, "region": "Western Africa", "continent": "Africa", "population": 546388, "country_name": "Cape Verde"}');
INSERT INTO country (country_sk, data) VALUES (4096, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 449568, "country_name": "Guadeloupe"}');
INSERT INTO country (country_sk, data) VALUES (4097, '{"gdp": 4520, "region": "Southern Asia", "continent": "Asia", "population": 436330, "country_name": "Maldives"}');
INSERT INTO country (country_sk, data) VALUES (4098, '{"gdp": 12011, "region": "Southern Europe", "continent": "Europe", "population": 430835, "country_name": "Malta"}');
INSERT INTO country (country_sk, data) VALUES (4099, '{"gdp": 11963, "region": "South-eastern Asia", "continent": "Asia", "population": 428697, "country_name": "Brunei"}');
INSERT INTO country (country_sk, data) VALUES (4100, '{"gdp": 9127, "region": "Caribbean", "continent": "Americas", "population": 395361, "country_name": "Bahamas"}');
INSERT INTO country (country_sk, data) VALUES (4101, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 384896, "country_name": "Martinique"}');
INSERT INTO country (country_sk, data) VALUES (4102, '{"gdp": 1819, "region": "Central America", "continent": "Americas", "population": 374681, "country_name": "Belize"}');
INSERT INTO country (country_sk, data) VALUES (4103, '{"gdp": 24848, "region": "Northern Europe", "continent": "Europe", "population": 335025, "country_name": "Iceland"}');
INSERT INTO country (country_sk, data) VALUES (4104, '{"gdp": 4821, "region": "Caribbean", "continent": "Americas", "population": 285719, "country_name": "Barbados"}');
INSERT INTO country (country_sk, data) VALUES (4105, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 283007, "country_name": "French Polynesia"}');
INSERT INTO country (country_sk, data) VALUES (4106, '{"gdp": null, "region": "South America", "continent": "Americas", "population": 282731, "country_name": "French Guiana"}');
INSERT INTO country (country_sk, data) VALUES (4107, '{"gdp": null, "region": "Melanesia", "continent": "Oceania", "population": 276255, "country_name": "New Caledonia"}');
INSERT INTO country (country_sk, data) VALUES (4108, '{"gdp": 837, "region": "Melanesia", "continent": "Oceania", "population": 276244, "country_name": "Vanuatu"}');
INSERT INTO country (country_sk, data) VALUES (4109, '{"gdp": null, "region": "Eastern Africa", "continent": "Africa", "population": 253045, "country_name": "Mayotte"}');
INSERT INTO country (country_sk, data) VALUES (4110, '{"gdp": 372, "region": "Middle Africa", "continent": "Africa", "population": 204327, "country_name": "Sao Tome and Principe"}');
INSERT INTO country (country_sk, data) VALUES (4111, '{"gdp": 844, "region": "Polynesia", "continent": "Oceania", "population": 196440, "country_name": "Samoa"}');
INSERT INTO country (country_sk, data) VALUES (4112, '{"gdp": 1717, "region": "Caribbean", "continent": "Americas", "population": 178844, "country_name": "Saint Lucia"}');
INSERT INTO country (country_sk, data) VALUES (4113, '{"gdp": null, "region": "Northern Europe", "continent": "Europe", "population": 165314, "country_name": "Guernsey�and��Jersey"}');
INSERT INTO country (country_sk, data) VALUES (4114, '{"gdp": null, "region": "Micronesia", "continent": "Oceania", "population": 164229, "country_name": "Guam"}');
INSERT INTO country (country_sk, data) VALUES (4115, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 160539, "country_name": "Cura�ao"}');
INSERT INTO country (country_sk, data) VALUES (4116, '{"gdp": 186, "region": "Micronesia", "continent": "Oceania", "population": 116398, "country_name": "Kiribati"}');
INSERT INTO country (country_sk, data) VALUES (4117, '{"gdp": 815, "region": "Caribbean", "continent": "Americas", "population": 109897, "country_name": "Saint Vincent and the Grenadines"}');
INSERT INTO country (country_sk, data) VALUES (4118, '{"gdp": 437, "region": "Polynesia", "continent": "Oceania", "population": 108020, "country_name": "Tonga"}');
INSERT INTO country (country_sk, data) VALUES (4119, '{"gdp": 1111, "region": "Caribbean", "continent": "Americas", "population": 107825, "country_name": "Grenada"}');
INSERT INTO country (country_sk, data) VALUES (4120, '{"gdp": 329, "region": "Micronesia", "continent": "Oceania", "population": 105544, "country_name": "Federated States of Micronesia"}');
INSERT INTO country (country_sk, data) VALUES (4121, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 105264, "country_name": "Aruba"}');
INSERT INTO country (country_sk, data) VALUES (4122, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 104901, "country_name": "United States Virgin Islands"}');
INSERT INTO country (country_sk, data) VALUES (4123, '{"gdp": 1535, "region": "Caribbean", "continent": "Americas", "population": 102012, "country_name": "Antigua and Barbuda"}');
INSERT INTO country (country_sk, data) VALUES (4124, '{"gdp": 1479, "region": "Eastern Africa", "continent": "Africa", "population": 94737, "country_name": "Seychelles"}');
INSERT INTO country (country_sk, data) VALUES (4125, '{"gdp": null, "region": "Northern Europe", "continent": "Europe", "population": 84287, "country_name": "Isle of Man"}');
INSERT INTO country (country_sk, data) VALUES (4126, '{"gdp": null, "region": "Southern Europe", "continent": "Europe", "population": 76965, "country_name": "Andorra"}');
INSERT INTO country (country_sk, data) VALUES (4127, '{"gdp": 608, "region": "Caribbean", "continent": "Americas", "population": 73925, "country_name": "Dominica"}');
INSERT INTO country (country_sk, data) VALUES (4128, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 61559, "country_name": "Cayman Islands"}');
INSERT INTO country (country_sk, data) VALUES (4129, '{"gdp": null, "region": "Northern America", "continent": "Americas", "population": 61349, "country_name": "Bermuda"}');
INSERT INTO country (country_sk, data) VALUES (4130, '{"gdp": null, "region": "Northern America", "continent": "Americas", "population": 56480, "country_name": "Greenland"}');
INSERT INTO country (country_sk, data) VALUES (4131, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 55641, "country_name": "American Samoa"}');
INSERT INTO country (country_sk, data) VALUES (4132, '{"gdp": 939, "region": "Caribbean", "continent": "Americas", "population": 55345, "country_name": "Saint Kitts and Nevis"}');
INSERT INTO country (country_sk, data) VALUES (4133, '{"gdp": null, "region": "Micronesia", "continent": "Oceania", "population": 55144, "country_name": "Northern Mariana Islands"}');
INSERT INTO country (country_sk, data) VALUES (4134, '{"gdp": 199, "region": "Micronesia", "continent": "Oceania", "population": 53127, "country_name": "Marshall Islands"}');
INSERT INTO country (country_sk, data) VALUES (4135, '{"gdp": null, "region": "Northern Europe", "continent": "Europe", "population": 49290, "country_name": "Faroe Islands"}');
INSERT INTO country (country_sk, data) VALUES (4136, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 40120, "country_name": "Sint Maarten"}');
INSERT INTO country (country_sk, data) VALUES (4137, '{"gdp": null, "region": "Western Europe", "continent": "Europe", "population": 38695, "country_name": "Monaco"}');
INSERT INTO country (country_sk, data) VALUES (4138, '{"gdp": null, "region": "Western Europe", "continent": "Europe", "population": 37922, "country_name": "Liechtenstein"}');
INSERT INTO country (country_sk, data) VALUES (4139, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 35446, "country_name": "Turks and Caicos Islands"}');
INSERT INTO country (country_sk, data) VALUES (4140, '{"gdp": null, "region": "Southern Europe", "continent": "Europe", "population": 34571, "country_name": "Gibraltar"}');
INSERT INTO country (country_sk, data) VALUES (4141, '{"gdp": 1592, "region": "Southern Europe", "continent": "Europe", "population": 33400, "country_name": "San Marino"}');
INSERT INTO country (country_sk, data) VALUES (4142, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 31196, "country_name": "British Virgin Islands"}');
INSERT INTO country (country_sk, data) VALUES (4143, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 25398, "country_name": "Caribbean Netherlands"}');
INSERT INTO country (country_sk, data) VALUES (4144, '{"gdp": 321, "region": "Micronesia", "continent": "Oceania", "population": 21729, "country_name": "Palau"}');
INSERT INTO country (country_sk, data) VALUES (4145, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 17380, "country_name": "Cook Islands"}');
INSERT INTO country (country_sk, data) VALUES (4146, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 14909, "country_name": "Anguilla"}');
INSERT INTO country (country_sk, data) VALUES (4147, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 11773, "country_name": "Wallis and Futuna"}');
INSERT INTO country (country_sk, data) VALUES (4148, '{"gdp": null, "region": "Micronesia", "continent": "Oceania", "population": 11359, "country_name": "Nauru"}');
INSERT INTO country (country_sk, data) VALUES (4149, '{"gdp": 40, "region": "Polynesia", "continent": "Oceania", "population": 11192, "country_name": "Tuvalu"}');
INSERT INTO country (country_sk, data) VALUES (4150, '{"gdp": null, "region": "Northern America", "continent": "Americas", "population": 6320, "country_name": "Saint Pierre and Miquelon"}');
INSERT INTO country (country_sk, data) VALUES (4151, '{"gdp": null, "region": "Caribbean", "continent": "Americas", "population": 5177, "country_name": "Montserrat"}');
INSERT INTO country (country_sk, data) VALUES (4152, '{"gdp": null, "region": "Western Africa", "continent": "Africa", "population": 4049, "country_name": "Saint Helena Ascension and Tristan da Cunha"}');
INSERT INTO country (country_sk, data) VALUES (4153, '{"gdp": null, "region": "South America", "continent": "Americas", "population": 2910, "country_name": "Falkland Islands"}');
INSERT INTO country (country_sk, data) VALUES (4154, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 1618, "country_name": "Niue"}');
INSERT INTO country (country_sk, data) VALUES (4155, '{"gdp": null, "region": "Polynesia", "continent": "Oceania", "population": 1300, "country_name": "Tokelau"}');
INSERT INTO country (country_sk, data) VALUES (4156, '{"gdp": null, "region": "Southern Europe", "continent": "Europe", "population": 792, "country_name": "Vatican City"}');
INSERT INTO country (country_sk, data) VALUES (4157, '{"gdp": 7536, "region": "Southern Europe", "continent": "Europe", "population": 1812000, "country_name": "Kosovo"}');
